# -*- coding: utf-8 -*-
"""Data_scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XNqJLhPASAIhq2AIRQxhGjZvim-gTIM
"""

import requests
import json
import pandas as pd

class FetchDescription:

    def __init__(self, headers, ids):
        self.headers = headers
        self.ids = ids

    # funtion to get all the metadata of the GTA cities
    def get_cities_metadata(self):

        fulldetails = {}
        listurl = "https://housesigma.com/bkv2/api/search/address_v2/suggest"

        gta_cities = [
            "Toronto", "Ajax", "Aurora", "Brampton", "Brock", "Burlington",
            "Caledon", "Clarington", "East Gwillimbury", "Georgina", "Markham",
            "Mississauga", "Milton", "Newmarket", "Oakville", "Oshawa", "Pickering",
            "Richmond Hill", "Scugog", "Vaughan", "Whitchurch-Stouffville", "Uxbridge",
            "King", "Halton Hills", "Whitby"
        ]
        for city in gta_cities:
            payload = {
                "lang": "en_US",
                "province": "ON",
                "search_term": city
            }
            response = requests.get(listurl, params=payload, headers=self.headers)
            # Check if the request was successful (status code 200)
            if response.status_code == 200:
                city_data = response.json()
                fulldetails[city] = city_data
            else:
                print("Error:", response.status_code)

        return fulldetails, gta_cities


    def get_description(self):
        ids = []
        province_name = []
        cross_street = []
        city = []

        # Adding 3 new features
        # picture = []
        status = []
        house_style = []    #key facts
        address = []

        bedroom = []
        washroom = []
        parking = []
        garage = []
        price = []
        area = []
        basement = []
        house_type = []
        description1 = []
        description2 = []


        formatted_id_descriptions = {}
        url = "https://housesigma.com/bkv2/api/listing/info/detail_v2"


        # Getting the ids with its corresponding descriptions
        for gta_id_list in self.ids:
            ids.append(gta_id_list)

            payload = {"lang": "en_US",
                       "province": "ON",
                       "id_address": "",
                       "id_listing": gta_id_list,
                       "event_source": "",
                       "signature": "12629da4579fe635518e06ef7f053191",
                       "ts": "1709347825"
                       }

            response = requests.get(url, params=payload, headers=self.headers)

            if response.status_code == 200:
                data = response.json()

            else:
                print("Error:", response.status_code)


            # Getting description1 and description 2 differently
            for key, value in data.items():

                if isinstance(value, dict) and 'house' in value:
                    house = value['house']

                    if 'price' in house:
                        price.append(house['price'])

                    if 'province_name' in house:
                        province_name.append(house['province_name'])

                    if 'cross_street' in house:
                        cross_street.append(house['cross_street'])

                    if 'bedroom' in house:
                        bedroom.append(house['bedroom'])

                    if 'washroom' in house:
                        washroom.append(house['washroom'])

                    if 'municipality_name' in house:
                        city.append(house['municipality_name'])

                    if 'parking' in house:
                        parking.append(house['parking']['parking'])
                        garage.append(house['parking']['garage'])

                    if 'house_type' in house:
                        house_type.append(house['house_type'])

                    if 'house_area' in house:
                        area.append(house['house_area']['estimate'])

                    if 'list_status' in house:
                        status.append(house['list_status']['s_r'])

                    if 'address' in house:
                        address.append(house['address'])


                if isinstance(value, dict) and 'key_facts' in value:

                    key_facts = value['key_facts']

                    if 'description1' in key_facts:
                        description1.append(key_facts['description1'])

                    if 'description2' in key_facts:
                        description2.append(key_facts['description2'])

                    if 'basement' in key_facts:
                        basement.append(key_facts['basement'])

                    if 'house_style' in key_facts:
                        house_style.append(key_facts['house_style'])

                    if description1 is not None and description2 is not None:
                        break


            for i, id in enumerate(ids):
                descriptions = {
                    "province_name": province_name[i],
                    "cross_street": cross_street[i],
                    "city": city[i],
                    "bedroom": bedroom[i],
                    "washroom": washroom[i],
                    "parking": parking[i],
                    "garage":  garage[i],
                    "price":  price[i],
                    "area": area[i],
                    "basement":  basement[i],
                    "house_type":  house_type[i],

                    "status": status[i],
                    "house_style": house_style[i],
                    "address": address[i],

                    "description1": description1[i],
                    "description2": description2[i]



                }
                formatted_id_descriptions[id] = descriptions

        json_formatted_id_descriptions = json.dumps(formatted_id_descriptions)
        return json_formatted_id_descriptions


headers = {
    #"Authorization": "Bearer 202401259ujl7r8cqoknievf8pj8qbg85u"
    #"Authorization": "Bearer 202402128ti2uiftk180fm9c29i0jev9ng"
    "Authorization": "Bearer 202402128ti2uiftk180fm9c29i0jev9ng"
}

fetch = FetchDescription(headers, [])

city_meta, all_cities = fetch.get_cities_metadata()
# print(all_ids)

gta_location_ids = []
for city in all_cities:
    for val in city_meta[city]['data']['house_list']:
        gta_location_ids.append(val['id_listing'])

fetch_description = FetchDescription(headers, gta_location_ids)

json_formatted_id_descriptions = fetch_description.get_description()

data_dict = json.loads(json_formatted_id_descriptions)
descriptions_df = pd.DataFrame.from_dict(data_dict, orient='index')
# descriptions_df.head(10)

descriptions_df.head(10)

#descriptions_df.to_csv("26March_Description_dataset.csv")

descriptions_df.to_csv("27March_part2_Description_dataset.csv")

